In [1]:
import gym
import ntwrk
import sys
sys.path.append("../ntwrk/gym/")
import network_sim

In [4]:
import numpy as np

In [2]:
env = gym.make('PccNs-v0')

History length: 10
Features: ['sent latency inflation', 'latency ratio', 'send ratio']
Getting min obs for ['sent latency inflation', 'latency ratio', 'send ratio']


/home/vagrant/.local/lib/python3.6/site-packages/gym/logger.py:30: UserWarning: WARN: Box bound precision lowered by casting to float32
  warnings.warn(colorize('%s: %s'%('WARN', msg % args), 'yellow'))


In [10]:
env.reset()

Reward: 0.00, Ewma Reward: 0.00


array([0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1.])

In [26]:
act = np.array([0.02])
send_obs, reward, stop_, _ = env.step(act)

Actions: [0.02]
[0.02]




In [27]:
send_obs

array([0.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 0.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       0.00000000e+00, 1.00000000e+00, 1.00000000e+00, 0.00000000e+00,
       1.00000000e+00, 1.00000000e+00, 0.00000000e+00, 1.00000000e+00,
       1.01142857e+00, 2.40841093e-16, 1.00000000e+00, 9.82758621e-01,
       0.00000000e+00, 1.00000000e+00, 9.82456140e-01, 0.00000000e+00,
       1.00000000e+00, 1.03703704e+00])

In [28]:
reward

0.16480532004861165

In [35]:
env.senders[0].get_run_data()

In [38]:
env.reset()

Reward: 1.14, Ewma Reward: 0.01


array([0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1.,
       1., 0., 1., 1., 0., 1., 1., 0., 1., 1., 0., 1., 1.])

In [39]:
env.event_record

{'Events': []}

In [40]:
env.step(act)

Actions: [0.02]
[0.02]




(array([0.        , 1.        , 1.        , 0.        , 1.        ,
        1.        , 0.        , 1.        , 1.        , 0.        ,
        1.        , 1.        , 0.        , 1.        , 1.        ,
        0.        , 1.        , 1.        , 0.        , 1.        ,
        1.        , 0.        , 1.        , 1.        , 0.        ,
        1.        , 1.        , 0.14473385, 1.        , 1.44262295]),
 2.8659841812099462,
 False,
 {})

In [42]:
env.event_record

{'Events': [{'Latency': 0.2351856337732246,
   'Latency Inflation': 0.14473385128098493,
   'Latency Ratio': 1.0,
   'Loss Rate': 0.0,
   'Name': 'Step',
   'Reward': 2.8659841812099462,
   'Send Rate': 5368582.499380702,
   'Send Ratio': 1.442622950819672,
   'Throughput': 3721403.777979805,
   'Time': 1}]}

In [43]:
env.senders[0].rate

445.7700412642881